package com.example.trulyiasapplication.DataModel

data class QuestionDataModelItem(
    val _links: Links,
    val author: Int,
    val categories: List<Int>,
    val comment_status: String,
    val content: Content,
    val date: String,
    val date_gmt: String,
    val excerpt: Excerpt,
    val featured_media: Int,
    val format: String,
    val guid: Guid,
    val id: Int,
    val jetpack_featured_media_url: String,
    val link: String,
    val meta: Meta,
    val modified: String,
    val modified_gmt: String,
    val ping_status: String,
    val rttpg_author: RttpgAuthor,
    val rttpg_category: String,
    val rttpg_comment: Int,
    val rttpg_excerpt: String,
    val rttpg_featured_image_url: Any?,
    val slug: String,
    val status: String,
    val sticky: Boolean,
    val tags: List<Any>,
    val template: String,
    val title: Title,
    val type: String,
    val yoast_head: String,
    val yoast_head_json: YoastHeadJson
)